# Configuration for processing ROS2 bag files
# This file specifies the paths, storage format, and topics to extract from the ROS bag.

# Path to the input ROS2 bag file
bag_path: "/workspace/rosbag2_2025_12_26-14_06_49"

# Directory where the exported data will be saved
output_dir: "/workspace/bags/extracted_dir_6/"

# Storage format for the exported data. Options are "sqlite3" or "mcap"
storage_id: "sqlite3"

# List of topics to extract from the ROS2 bag
topics:
  # Configuration for the RGB image topic
  - name: "/camera/camera/color/image_raw/compressed"    # Name of the topic to extract
    type: "CompressedImage"               # Data type of the topic
    encoding: "rgb8"            # Encoding format for the image
    sample_interval: 5          # Write one sample every 5 messages
